apiVersion: v1  
kind: Service  
metadata:  
  name: cwvj-devsecops-demo-svc  
  namespace: cwvj-devsecops
  labels:  
    app: cwvj-devsecops-demo  
spec:  
  type: NodePort  
  selector:  
    app: cwvj-devsecops-demo  
  ports:  
    - port: 80  
      targetPort: 8080  
      protocol: TCP  
      nodePort: 31000  